/**
 * GET  /api/catches        — list catches for the authenticated user
 * POST /api/catches        — create a new catch record (mobile app)
 *
 * Query params (GET):
 *   limit?   number  default 50, max 200
 *   offset?  number  default 0
 *   status?  'identified' | 'unnamed' | 'pending_curation'  (filter by identification status)
 *   public?  'true' | 'false'  (filter by visibility)
 *
 * Body (POST, JSON):
 *   species              string   required unless identification_status is 'unnamed'
 *   scientific_name?     string
 *   weight_kg?           number
 *   length_cm?           number
 *   bait?                string
 *   technique?           string
 *   location_name?       string
 *   latitude?            number
 *   longitude?           number
 *   emirate?             string
 *   photo_url?           string
 *   notes?               string
 *   is_public?           boolean  default true
 *   caught_at?           ISO string  default now
 *   rfid_tag?            string
 *   identification_status? 'identified' | 'unnamed' | 'pending_curation'
 *   unnamed_key?         string   (generated by /api/identify if status is 'unnamed')
 *   identify_id?         string   (uuid from /api/identify — overrides client-supplied
 *                                  species/scientific_name with the audited values)
 *   water_colour?        string
 *   pollution_type?      string
 *   pollution_severity?  string
 *   water_temp_c?        number
 *   visibility_m?        number
 *   video_url?           string   — video URL where this catch appears (YouTube/TikTok/Reels/Facebook)
 *   source?              string   — 'web' | 'app' | 'ocean_sentinel'  default 'web'
 *
 * Auth: Bearer token required
 */

import { NextRequest, NextResponse } from 'next/server';
import { requireAuth, getUserSupabase } from '@/lib/api-auth';

export async function GET(req: NextRequest) {
  const auth = await requireAuth(req);
  if (!auth.ok) return auth.response;

  const { searchParams } = new URL(req.url);
  const limit  = Math.min(200, Math.max(1, Number(searchParams.get('limit')  ?? 50)));
  const offset = Math.max(0, Number(searchParams.get('offset') ?? 0));
  const status = searchParams.get('status');
  const pub    = searchParams.get('public');

  const sb = getUserSupabase(auth.token);
  let query = sb
    .from('catches')
    .select('*')
    .eq('user_id', auth.user.id)
    .order('caught_at', { ascending: false })
    .range(offset, offset + limit - 1);

  if (status) query = query.eq('identification_status', status);
  if (pub !== null) query = query.eq('is_public', pub === 'true');

  const { data, error, count } = await query;
  if (error) {
    console.error('[catches GET]', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ catches: data, count: count ?? data?.length ?? 0 });
}

export async function POST(req: NextRequest) {
  const auth = await requireAuth(req);
  if (!auth.ok) return auth.response;

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const status = (body.identification_status as string) ?? 'identified';

  // Species is required unless the catch is unnamed/pending curation, OR the
  // client supplied an identify_id — in that case the server pulls species
  // from the audit row further down.
  if (!body.species && !body.identify_id && status === 'identified') {
    return NextResponse.json({ error: 'species is required for identified catches' }, { status: 400 });
  }

  // Validate GPS bounds
  if (body.latitude != null) {
    const lat = Number(body.latitude);
    if (lat < -90 || lat > 90) {
      return NextResponse.json({ error: `Invalid latitude: ${lat}` }, { status: 400 });
    }
  }
  if (body.longitude != null) {
    const lon = Number(body.longitude);
    if (lon < -180 || lon > 180) {
      return NextResponse.json({ error: `Invalid longitude: ${lon}` }, { status: 400 });
    }
  }

  const sb = getUserSupabase(auth.token);

  // ── Resolve identify_id → trusted species + confidence ─────────────────
  // When the client passes an identify_id from a prior /api/identify call,
  // we overwrite any species/scientific_name/confidence the client supplied
  // with the values the server actually returned. This stops a logged catch
  // from claiming a different species or inflated confidence than what
  // Claude actually saw.
  let identifyId: string | null = null;
  let identifyConfidence: number | null = null;
  let trustedSpecies: string | null = null;
  let trustedScientificName: string | null = null;

  if (body.identify_id != null) {
    const { data: audit, error: auditErr } = await sb
      .from('identify_audits')
      .select('id, status, species, scientific_name, confidence_pct, expires_at')
      .eq('id', body.identify_id as string)
      .maybeSingle();
    if (auditErr) {
      console.error('[catches POST] identify lookup failed:', auditErr);
      return NextResponse.json({ error: auditErr.message }, { status: 500 });
    }
    if (!audit) {
      return NextResponse.json({ error: 'identify_id not found or not owned by you' }, { status: 404 });
    }
    if (new Date(audit.expires_at) < new Date()) {
      return NextResponse.json({ error: 'identify_id expired — identify the fish again' }, { status: 410 });
    }

    identifyId = audit.id;
    identifyConfidence = audit.confidence_pct;
    if (audit.status === 'identified') {
      trustedSpecies = audit.species;
      trustedScientificName = audit.scientific_name;
    }
  }

  const effectiveStatus = identifyId && trustedSpecies
    ? 'identified'
    : identifyId
      ? 'unnamed'
      : status;

  const effectiveSpecies =
    trustedSpecies
    ?? (body.species as string | undefined)
    ?? (body.unnamed_key as string | undefined)
    ?? 'Unknown';

  const { data, error } = await sb
    .from('catches')
    .insert({
      user_id:               auth.user.id,
      species:               effectiveSpecies,
      scientific_name:       trustedScientificName ?? body.scientific_name ?? null,
      identify_id:           identifyId,
      identify_confidence:   identifyConfidence,
      weight_kg:             body.weight_kg         != null ? Number(body.weight_kg)    : null,
      length_cm:             body.length_cm         != null ? Number(body.length_cm)    : null,
      bait:                  body.bait              ?? null,
      technique:             body.technique         ?? null,
      location_name:         body.location_name     ?? null,
      latitude:              body.latitude          != null ? Number(body.latitude)     : null,
      longitude:             body.longitude         != null ? Number(body.longitude)    : null,
      emirate:               body.emirate           ?? null,
      photo_url:             body.photo_url         ?? null,
      notes:                 body.notes             ?? null,
      is_public:             body.is_public         != null ? Boolean(body.is_public)   : true,
      caught_at:             body.caught_at         ?? new Date().toISOString(),
      rfid_tag:              body.rfid_tag          ?? null,
      identification_status: effectiveStatus,
      unnamed_key:           body.unnamed_key       ?? null,
      water_colour:          body.water_colour      ?? null,
      pollution_type:        body.pollution_type    ?? null,
      pollution_severity:    body.pollution_severity ?? null,
      water_temp_c:          body.water_temp_c      != null ? Number(body.water_temp_c) : null,
      visibility_m:          body.visibility_m      != null ? Number(body.visibility_m) : null,
      video_url:             body.video_url         ?? null,
      source:                (body.source as string) ?? 'app',
    })
    .select()
    .single();

  if (error) {
    console.error('[catches POST]', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ catch: data }, { status: 201 });
}
