/**
 * GET  /api/catches        — list catches for the authenticated user
 * POST /api/catches        — create a new catch record (mobile app)
 *
 * Query params (GET):
 *   limit?   number  default 50, max 200
 *   offset?  number  default 0
 *   status?  'identified' | 'unnamed' | 'pending_curation'  (filter by identification status)
 *   public?  'true' | 'false'  (filter by visibility)
 *
 * Body (POST, JSON):
 *   species              string   required unless identification_status is 'unnamed'
 *   scientific_name?     string
 *   weight_kg?           number
 *   length_cm?           number
 *   bait?                string
 *   technique?           string
 *   location_name?       string
 *   latitude?            number
 *   longitude?           number
 *   emirate?             string
 *   photo_url?           string
 *   notes?               string
 *   is_public?           boolean  default true
 *   caught_at?           ISO string  default now
 *   rfid_tag?            string
 *   identification_status? 'identified' | 'unnamed' | 'pending_curation'
 *   unnamed_key?         string   (generated by /api/identify if status is 'unnamed')
 *   identify_id?         string   (uuid from /api/identify — overrides client-supplied
 *                                  species/scientific_name with the audited values)
 *   water_colour?        string
 *   pollution_type?      string
 *   pollution_severity?  string
 *   water_temp_c?        number
 *   visibility_m?        number
 *   video_url?           string   — video URL where this catch appears (YouTube/TikTok/Reels/Facebook)
 *   source?              string   — 'web' | 'app' | 'ocean_sentinel'  default 'web'
 *
 * Auth: Bearer token required
 */

import { NextRequest, NextResponse } from 'next/server';
import { requireAuth, getUserSupabase } from '@/lib/api-auth';
import { z } from 'zod';

const postSchema = z.object({
  species: z.string().optional(),
  scientific_name: z.string().optional(),
  weight_kg: z.number().optional(),
  length_cm: z.number().optional(),
  bait: z.string().optional(),
  technique: z.string().optional(),
  location_name: z.string().optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
  emirate: z.string().optional(),
  photo_url: z.string().optional(),
  notes: z.string().optional(),
  is_public: z.boolean().optional(),
  caught_at: z.string().optional(),
  rfid_tag: z.string().optional(),
  identification_status: z.enum(['identified', 'unnamed', 'pending_curation']).optional(),
  unnamed_key: z.string().optional(),
  identify_id: z.string().optional(),
  water_colour: z.string().optional(),
  pollution_type: z.string().optional(),
  pollution_severity: z.string().optional(),
  water_temp_c: z.number().optional(),
  visibility_m: z.number().optional(),
  video_url: z.string().optional(),
  source: z.string().optional(),
});

export async function GET(req: NextRequest) {
  const auth = await requireAuth(req);
  if (!auth.ok) return auth.response;

  const { searchParams } = new URL(req.url);
  const limit  = Math.min(200, Math.max(1, Number(searchParams.get('limit')  ?? 50)));
  const offset = Math.max(0, Number(searchParams.get('offset') ?? 0));
  const status = searchParams.get('status');
  const pub    = searchParams.get('public');

  const sb = getUserSupabase(auth.token);
  let query = sb
    .from('catches')
    .select('*')
    .eq('user_id', auth.user.id)
    .order('caught_at', { ascending: false })
    .range(offset, offset + limit - 1);

  if (status) query = query.eq('identification_status', status);
  if (pub !== null) query = query.eq('is_public', pub === 'true');

  const { data, error, count } = await query;
  if (error) {
    console.error('[catches GET]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }

  return NextResponse.json({ catches: data, count: count ?? data?.length ?? 0 });
}

export async function POST(req: NextRequest) {
  try {
    const auth = await requireAuth(req);
    if (!auth.ok) return auth.response;

    const body = await req.json();
    const parsed = postSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: 'Invalid request body', issues: parsed.error.issues },
        { status: 400 },
      );
    }
    const data = parsed.data;

    const status = data.identification_status ?? 'identified';

    // Species is required unless the catch is unnamed/pending curation, OR the
    // client supplied an identify_id — in that case the server pulls species
    // from the audit row further down.
    if (!data.species && !data.identify_id && status === 'identified') {
      return NextResponse.json({ error: 'species is required for identified catches' }, { status: 400 });
    }

    // Validate GPS bounds
    if (data.latitude != null) {
      if (data.latitude < -90 || data.latitude > 90) {
        return NextResponse.json({ error: `Invalid latitude: ${data.latitude}` }, { status: 400 });
      }
    }
    if (data.longitude != null) {
      if (data.longitude < -180 || data.longitude > 180) {
        return NextResponse.json({ error: `Invalid longitude: ${data.longitude}` }, { status: 400 });
      }
    }

    const sb = getUserSupabase(auth.token);

    // ── Resolve identify_id → trusted species + confidence ─────────────────
    // When the client passes an identify_id from a prior /api/identify call,
    // we overwrite any species/scientific_name/confidence the client supplied
    // with the values the server actually returned. This stops a logged catch
    // from claiming a different species or inflated confidence than what
    // Claude actually saw.
    let identifyId: string | null = null;
    let identifyConfidence: number | null = null;
    let trustedSpecies: string | null = null;
    let trustedScientificName: string | null = null;

    if (data.identify_id != null) {
      const { data: audit, error: auditErr } = await sb
        .from('identify_audits')
        .select('id, status, species, scientific_name, confidence_pct, expires_at')
        .eq('id', data.identify_id)
        .maybeSingle();
      if (auditErr) {
        console.error('[catches POST] identify lookup failed:', auditErr);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
      }
      if (!audit) {
        return NextResponse.json({ error: 'identify_id not found or not owned by you' }, { status: 404 });
      }
      if (new Date(audit.expires_at) < new Date()) {
        return NextResponse.json({ error: 'identify_id expired — identify the fish again' }, { status: 410 });
      }

      identifyId = audit.id;
      identifyConfidence = audit.confidence_pct;
      if (audit.status === 'identified') {
        trustedSpecies = audit.species;
        trustedScientificName = audit.scientific_name;
      }
    }

    const effectiveStatus = identifyId && trustedSpecies
      ? 'identified'
      : identifyId
        ? 'unnamed'
        : status;

    const effectiveSpecies =
      trustedSpecies
      ?? data.species
      ?? data.unnamed_key
      ?? 'Unknown';

    const { data: inserted, error } = await sb
      .from('catches')
      .insert({
        user_id:               auth.user.id,
        species:               effectiveSpecies,
        scientific_name:       trustedScientificName ?? data.scientific_name ?? null,
        identify_id:           identifyId,
        identify_confidence:   identifyConfidence,
        weight_kg:             data.weight_kg         ?? null,
        length_cm:             data.length_cm         ?? null,
        bait:                  data.bait              ?? null,
        technique:             data.technique         ?? null,
        location_name:         data.location_name     ?? null,
        latitude:              data.latitude          ?? null,
        longitude:             data.longitude         ?? null,
        emirate:               data.emirate           ?? null,
        photo_url:             data.photo_url         ?? null,
        notes:                 data.notes             ?? null,
        is_public:             data.is_public         ?? true,
        caught_at:             data.caught_at         ?? new Date().toISOString(),
        rfid_tag:              data.rfid_tag          ?? null,
        identification_status: effectiveStatus,
        unnamed_key:           data.unnamed_key       ?? null,
        water_colour:          data.water_colour      ?? null,
        pollution_type:        data.pollution_type    ?? null,
        pollution_severity:    data.pollution_severity ?? null,
        water_temp_c:          data.water_temp_c      ?? null,
        visibility_m:          data.visibility_m      ?? null,
        video_url:             data.video_url         ?? null,
        source:                data.source            ?? 'app',
      })
      .select()
      .single();

    if (error) {
      console.error('[catches POST]', error);
      return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }

    return NextResponse.json({ catch: inserted }, { status: 201 });
  } catch (error) {
    console.error('[catches POST]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
