/**
 * UAE Fishing Regulations
 *
 * Primary source: MOCCAE (Ministry of Climate Change and Environment)
 * Secondary sources: EAD (Environment Agency Abu Dhabi), Dubai Municipality,
 *   Sharjah EAA, and respective emirate authorities.
 *
 * Legal basis: Federal Law No. 23 of 1999 on the Exploitation, Protection and
 * Development of Living Aquatic Resources, and subsequent Ministerial Decisions.
 */

export interface RegulationEntry {
  id: string;
  title: string;
  regulation_type:
    | 'seasonal_ban'
    | 'size_limit'
    | 'protected_species'
    | 'gear_restriction'
    | 'licensing'
    | 'marine_protected_area'
    | 'general';
  description: string;
  species_names: string[];
  species_slugs: string[];
  ban_start_month: number | null;
  ban_start_day: number | null;
  ban_end_month: number | null;
  ban_end_day: number | null;
  ban_scope: string | null;
  min_size_cm: number | null;
  min_weight_kg: number | null;
  authority: string;
  authority_type: 'federal' | 'emirate';
  emirate: string | null; // null = UAE-wide
  legal_ref: string | null;
  source_url: string | null;
  applies_to_coast: 'Persian Gulf' | 'Gulf of Oman' | 'Both' | null;
  applies_to_all_species: boolean;
  notes: string | null;
}

export const regulations: RegulationEntry[] = [

  // ─── SEASONAL BANS ─────────────────────────────────────────────────────────

  {
    id: 'ban-hammour-summer',
    title: 'Hammour & Grouper Seasonal Fishing Ban',
    regulation_type: 'seasonal_ban',
    description:
      'Complete ban on fishing, catching, possessing, selling, buying and transporting Hammour (Orange-spotted Grouper) and related grouper species during their spawning season. The ban applies to commercial and recreational fishing. Violators face fines up to AED 500,000 under Federal Law No. 23 of 1999.',
    species_names: ['Hammour (Orange-spotted Grouper)', 'Duskytail Grouper', 'Areolate Grouper'],
    species_slugs: ['hammour', 'duskytail-grouper', 'areolate-grouper'],
    ban_start_month: 7,
    ban_start_day: 1,
    ban_end_month: 8,
    ban_end_day: 31,
    ban_scope: 'all',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Ministerial Decision No. 74 of 2020; Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: 'Ban dates confirmed annually by MOCCAE. Check for updates before the season.',
  },

  {
    id: 'ban-shari-spawning',
    title: 'Shari (Spangled Emperor) Spawning Season Ban',
    regulation_type: 'seasonal_ban',
    description:
      'Fishing for Shari is prohibited during its spawning aggregation period. This protects one of the most commercially important reef fish species in UAE waters from overharvesting during its most vulnerable period.',
    species_names: ['Shari (Spangled Emperor)'],
    species_slugs: ['spangled-emperor'],
    ban_start_month: 2,
    ban_start_day: 1,
    ban_end_month: 3,
    ban_end_day: 31,
    ban_scope: 'all',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Ministerial Decision No. 74 of 2020; Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: null,
  },

  {
    id: 'ban-zubaidi-spawning',
    title: 'Zubaidi (Silver Pomfret) Seasonal Ban',
    regulation_type: 'seasonal_ban',
    description:
      'Silver Pomfret (Zubaidi) fishing is banned during the peak spawning months of May and June. This is a high-value species frequently traded in UAE fish markets and is subject to significant fishing pressure.',
    species_names: ['Silver Pomfret (Zubaidi)'],
    species_slugs: ['silver-pomfret'],
    ban_start_month: 5,
    ban_start_day: 1,
    ban_end_month: 6,
    ban_end_day: 30,
    ban_scope: 'all',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Persian Gulf',
    applies_to_all_species: false,
    notes: null,
  },

  {
    id: 'ban-shrimp-trawling',
    title: 'Shrimp Trawling Seasonal Closure',
    regulation_type: 'seasonal_ban',
    description:
      'Commercial shrimp trawling is banned from March to August each year to protect juvenile shrimp populations during recruitment season. This closure covers UAE territorial waters on the Persian Gulf side.',
    species_names: [],
    species_slugs: [],
    ban_start_month: 3,
    ban_start_day: 1,
    ban_end_month: 8,
    ban_end_day: 31,
    ban_scope: 'commercial trawling',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999, Article 28',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Persian Gulf',
    applies_to_all_species: false,
    notes: 'Applies to commercial trawling vessels. Recreational fishing not affected.',
  },

  // ─── MINIMUM SIZE LIMITS ───────────────────────────────────────────────────

  {
    id: 'size-hammour',
    title: 'Hammour Minimum Size: 40 cm',
    regulation_type: 'size_limit',
    description:
      'The minimum legal landing size for Hammour (Orange-spotted Grouper) is 40 cm total length. Fish below this size must be immediately returned to the water alive. This size corresponds approximately to the age of first sexual maturity.',
    species_names: ['Hammour (Orange-spotted Grouper)'],
    species_slugs: ['hammour'],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: 40,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Ministerial Decision No. 74 of 2020',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: 'Measured as total length (tip of snout to end of tail fin).',
  },

  {
    id: 'size-shari',
    title: 'Shari (Spangled Emperor) Minimum Size: 25 cm',
    regulation_type: 'size_limit',
    description:
      'Spangled Emperor (Shari/Lethrinus nebulosus) must measure at least 25 cm total length before being retained. Undersized fish must be returned alive.',
    species_names: ['Shari (Spangled Emperor)'],
    species_slugs: ['spangled-emperor'],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: 25,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: null,
  },

  {
    id: 'size-sultan-ibrahim',
    title: 'Sultan Ibrahim (Red Mullet) Minimum Size: 15 cm',
    regulation_type: 'size_limit',
    description:
      'Red Mullet (Sultan Ibrahim / Mullidae family) must be at least 15 cm total length. This small but commercially important species is heavily targeted in UAE waters.',
    species_names: ['Sultan Ibrahim (Red Mullet)'],
    species_slugs: ['sultan-ibrahim'],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: 15,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: null,
  },

  {
    id: 'size-zubaidi',
    title: 'Zubaidi (Silver Pomfret) Minimum Size: 20 cm',
    regulation_type: 'size_limit',
    description:
      'Silver Pomfret (Zubaidi) must be at least 20 cm total length. As one of the most prized food fish in the UAE, Zubaidi faces significant commercial and recreational harvest pressure.',
    species_names: ['Silver Pomfret (Zubaidi)'],
    species_slugs: ['silver-pomfret'],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: 20,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Persian Gulf',
    applies_to_all_species: false,
    notes: null,
  },

  {
    id: 'size-kingfish',
    title: 'Kingfish (Narrow-barred Mackerel) Minimum Size: 55 cm',
    regulation_type: 'size_limit',
    description:
      'Narrow-barred Spanish Mackerel (Kingfish / Scomberomorus commerson) must measure at least 55 cm total length. Kingfish is a highly prized game and food fish in UAE waters and subject to intense targeting.',
    species_names: ['Kingfish (Narrow-barred Mackerel)'],
    species_slugs: ['narrow-barred-mackerel'],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: 55,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: null,
  },

  {
    id: 'size-hamra',
    title: 'Hamra (Red Snapper family) Minimum Size: 25 cm',
    regulation_type: 'size_limit',
    description:
      'Red Snapper and related Lutjanidae family (Hamra) must be at least 25 cm total length before being retained.',
    species_names: ['One-spot Snapper'],
    species_slugs: ['one-spot-snapper'],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: 25,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: null,
  },

  {
    id: 'size-farsh',
    title: 'Farsh (Spinefoot / Rabbitfish) Minimum Size: 15 cm',
    regulation_type: 'size_limit',
    description:
      'Siganidae (Spinefoot / Farsh) species must be at least 15 cm total length. Handle Farsh with care — their dorsal spines are venomous.',
    species_names: ['Streaked Spinefoot (Farsh)'],
    species_slugs: ['streaked-spinefoot'],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: 15,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: 'Spines are venomous — use a wet cloth when handling.',
  },

  // ─── FULLY PROTECTED SPECIES ───────────────────────────────────────────────

  {
    id: 'protected-sharks',
    title: 'All Shark Species — Fully Protected',
    regulation_type: 'protected_species',
    description:
      'All shark species found in UAE waters are fully protected under federal law. It is prohibited to fish, catch, possess, sell, buy, transport or export any shark or shark products (fins, meat, liver oil). The shark fin trade is explicitly banned. Violations carry fines up to AED 1,000,000.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: 'all activities',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999; Ministerial Decision No. 43 of 2012 (shark fin trade ban)',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: 'If accidentally hooked, cut the line immediately and do not remove the shark from the water.',
  },

  {
    id: 'protected-rays',
    title: 'All Ray Species — Fully Protected',
    regulation_type: 'protected_species',
    description:
      'All ray species including eagle rays, manta rays, sting rays and electric rays are fully protected in UAE waters. Accidental bycatch must be returned to the sea immediately without harm.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: 'all activities',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: null,
  },

  {
    id: 'protected-sea-turtles',
    title: 'All Sea Turtles — Fully Protected',
    regulation_type: 'protected_species',
    description:
      'All five sea turtle species found in UAE waters (Green Turtle, Hawksbill, Loggerhead, Leatherback, Olive Ridley) are fully protected. It is illegal to catch, harm, collect eggs, or disturb nesting females. UAE is home to globally significant Green Turtle nesting beaches.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: 'all activities',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999; CITES Appendix I',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: 'If a turtle is accidentally entangled, carefully disentangle without removing it from the water. Report incidents to MOCCAE.',
  },

  {
    id: 'protected-dugong',
    title: 'Dugong — Fully Protected',
    regulation_type: 'protected_species',
    description:
      'The Dugong (Dugong dugon) is fully protected throughout UAE waters. The UAE hosts one of the world\'s largest dugong populations, particularly in Abu Dhabi\'s Marawah Marine Biosphere Reserve. Any harassment, fishing for, or harm to dugongs is strictly illegal.',
    species_names: ['Dugong'],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: 'all activities',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE / EAD',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999; CITES Appendix I; EAD Decree',
    source_url: 'https://www.ead.gov.ae',
    applies_to_coast: 'Persian Gulf',
    applies_to_all_species: false,
    notes: null,
  },

  {
    id: 'protected-whale-shark',
    title: 'Whale Shark — Fully Protected',
    regulation_type: 'protected_species',
    description:
      'The Whale Shark (Rhincodon typus) is fully protected. It is illegal to fish for, injure, chase, or handle whale sharks. Boats must maintain a minimum 3-metre distance from whale sharks and may not operate directly above them. UAE waters are an important aggregation site for juvenile whale sharks.',
    species_names: ['Whale Shark'],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: 'all activities',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999; CITES Appendix II',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: null,
  },

  {
    id: 'protected-dolphins-whales',
    title: 'Dolphins & Whales — Fully Protected',
    regulation_type: 'protected_species',
    description:
      'All cetaceans (dolphins and whales) found in UAE waters are fully protected. This includes the Indo-Pacific Bottlenose Dolphin, Spinner Dolphin, Humpback Whale, and others. Deliberate harassment, pursuit, or harm is prohibited.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: 'all activities',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: null,
  },

  {
    id: 'protected-seahorses',
    title: 'Seahorses — Fully Protected',
    regulation_type: 'protected_species',
    description:
      'All seahorse species (Hippocampus spp.) are fully protected in the UAE. They may not be collected, kept, sold or exported. Seahorses are commonly found in UAE seagrass beds.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: 'all activities',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999; CITES Appendix II',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: false,
    notes: null,
  },

  // ─── GEAR RESTRICTIONS ─────────────────────────────────────────────────────

  {
    id: 'gear-trawling-ban',
    title: 'Bottom Trawling Prohibited Within 6 Nautical Miles',
    regulation_type: 'gear_restriction',
    description:
      'Bottom trawling is prohibited within 6 nautical miles of the UAE coastline. This protects coastal habitats including seagrass beds, coral reefs and soft-bottom communities from destructive trawl gear. Trawl vessels operating beyond 6nm require a commercial licence.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999, Articles 28–30',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: true,
    notes: null,
  },

  {
    id: 'gear-explosives-poison',
    title: 'Explosives, Poisons & Electrical Devices Prohibited',
    regulation_type: 'gear_restriction',
    description:
      'The use of explosives (dynamite fishing), poisonous substances, or electrical devices to stun, kill or catch fish is strictly prohibited throughout UAE waters. Violations carry severe criminal penalties including imprisonment.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999, Article 31',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: true,
    notes: null,
  },

  {
    id: 'gear-nets-permit',
    title: 'Net Fishing Requires a Commercial Permit',
    regulation_type: 'gear_restriction',
    description:
      'The use of cast nets, gill nets, beach seines and other net gear for the purpose of selling fish commercially requires a valid commercial fishing permit issued by MOCCAE. Recreational anglers may use small cast nets for personal use only.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: true,
    notes: null,
  },

  // ─── LICENSING ─────────────────────────────────────────────────────────────

  {
    id: 'licence-recreational',
    title: 'Recreational Fishing Licence Required for All',
    regulation_type: 'licensing',
    description:
      'All persons fishing recreationally in UAE waters require a valid fishing licence issued by MOCCAE. UAE nationals receive licences free of charge. Expatriate residents must pay a nominal annual fee. Licences are available online via the MOCCAE smart app or at MOCCAE service centres.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999, Article 14',
    source_url: 'https://moccae.gov.ae/en/services/fishing-license.aspx',
    applies_to_coast: 'Both',
    applies_to_all_species: true,
    notes: 'Fishing without a licence is subject to fines. Carry your licence while fishing.',
  },

  {
    id: 'licence-commercial',
    title: 'Commercial Fishing Licence — Separate Permit Required',
    regulation_type: 'licensing',
    description:
      'Commercial fishing — defined as fishing for the purpose of selling the catch — requires a separate commercial fishing licence in addition to vessel registration. Commercial licences are issued by MOCCAE in coordination with the respective emirate authority.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999, Articles 14–18',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: true,
    notes: null,
  },

  // ─── MARINE PROTECTED AREAS ────────────────────────────────────────────────

  {
    id: 'mpa-marawah',
    title: 'Marawah Marine Biosphere Reserve — No-Take Zone',
    regulation_type: 'marine_protected_area',
    description:
      'The Marawah Marine Biosphere Reserve (Abu Dhabi) covers 4,220 km² and is a UNESCO-recognised biosphere reserve. Fishing is strictly prohibited within the core zone. Buffer zones permit limited traditional fishing only. It protects the world\'s second-largest dugong population, nesting sea turtles, and extensive seagrass meadows.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: 'core zone — no fishing',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'EAD (Environment Agency Abu Dhabi)',
    authority_type: 'emirate',
    emirate: 'Abu Dhabi',
    legal_ref: 'EAD Decision No. 5 of 2007; UNESCO MAB Programme',
    source_url: 'https://www.ead.gov.ae',
    applies_to_coast: 'Persian Gulf',
    applies_to_all_species: true,
    notes: 'GPS boundaries available from EAD. Penalties for fishing in core zone are severe.',
  },

  {
    id: 'mpa-sir-bani-yas',
    title: 'Sir Bani Yas & Dalma Island Marine Protected Area',
    regulation_type: 'marine_protected_area',
    description:
      'The marine area surrounding Sir Bani Yas and Dalma Island is a protected zone managed by EAD. Commercial fishing and spearfishing are prohibited. Recreational fishing from shore is permitted in designated areas only.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: 'commercial and spear fishing prohibited',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'EAD (Environment Agency Abu Dhabi)',
    authority_type: 'emirate',
    emirate: 'Abu Dhabi',
    legal_ref: 'EAD Protected Areas Decree',
    source_url: 'https://www.ead.gov.ae',
    applies_to_coast: 'Persian Gulf',
    applies_to_all_species: true,
    notes: null,
  },

  {
    id: 'mpa-ras-al-khor',
    title: 'Ras Al Khor Wildlife Sanctuary — No Fishing',
    regulation_type: 'marine_protected_area',
    description:
      'Ras Al Khor Wildlife Sanctuary in Dubai is a Ramsar-listed wetland. All fishing, including shore fishing, is prohibited within the sanctuary boundaries. The area provides critical habitat for flamingos, herons, and numerous wading bird species.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: 'no fishing',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'Dubai Municipality',
    authority_type: 'emirate',
    emirate: 'Dubai',
    legal_ref: 'Dubai Municipality Decision; Ramsar Convention listing 2007',
    source_url: 'https://www.dm.gov.ae',
    applies_to_coast: 'Persian Gulf',
    applies_to_all_species: true,
    notes: 'Located at the junction of Dubai Creek and the Dubai Creek Harbour development.',
  },

  {
    id: 'mpa-al-zorah',
    title: 'Al Zorah Nature Reserve — Fishing Restrictions',
    regulation_type: 'marine_protected_area',
    description:
      'Al Zorah Nature Reserve in Ajman is a protected mangrove and coastal wetland. Fishing in the core mangrove channels is prohibited without prior permission from the Ajman Tourism Development Department. The reserve supports important nursery habitat for juvenile fish.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: 'permit required in mangrove core zone',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'Ajman Tourism & Development Department',
    authority_type: 'emirate',
    emirate: 'Ajman',
    legal_ref: 'Ajman Emiri Decree No. 2 of 2013',
    source_url: null,
    applies_to_coast: 'Persian Gulf',
    applies_to_all_species: true,
    notes: 'Shore fishing from the public beach at the perimeter is permitted.',
  },

  {
    id: 'mpa-funn-island',
    title: 'Funn Island (Siniya Island, UAQ) — No-Take Zone',
    regulation_type: 'marine_protected_area',
    description:
      'Siniya Island in Umm Al Quwain is a protected area for nesting birds and marine life. Fishing near the island is restricted. Consult UAQ Municipality for current boundaries.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: 'restricted fishing zone',
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'UAQ Municipality',
    authority_type: 'emirate',
    emirate: 'Umm Al Quwain',
    legal_ref: null,
    source_url: null,
    applies_to_coast: 'Persian Gulf',
    applies_to_all_species: true,
    notes: null,
  },

  // ─── GENERAL RULES ─────────────────────────────────────────────────────────

  {
    id: 'general-catch-report',
    title: 'Catch Reporting for Commercial Fishers',
    regulation_type: 'general',
    description:
      'Licensed commercial fishers are required to report their catch data to MOCCAE. This data feeds into national fisheries stock assessments. Recreational anglers are encouraged (but not currently required) to log catches via platforms like UAE Anglers Hub.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: true,
    notes: 'Log your catches at uaeangler.com/log-catch to contribute to UAE citizen science data.',
  },

  {
    id: 'general-spearfishing',
    title: 'Spearfishing — SCUBA Spearing Prohibited',
    regulation_type: 'gear_restriction',
    description:
      'Spearfishing using SCUBA equipment is prohibited throughout UAE waters. Free-dive spearfishing (breath-hold only) is permitted for recreational anglers with a valid fishing licence but is prohibited within designated marine protected areas.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: true,
    notes: 'Spearguns may not be carried on diving boats without a permit.',
  },

  {
    id: 'general-coral-protection',
    title: 'Coral and Seagrass — No Collection or Damage',
    regulation_type: 'general',
    description:
      'The collection, removal, damage or destruction of coral (live or dead) and seagrass is prohibited throughout UAE waters. Anchoring on coral reefs is illegal. Boats should use designated mooring buoys or anchor on sand.',
    species_names: [],
    species_slugs: [],
    ban_start_month: null,
    ban_start_day: null,
    ban_end_month: null,
    ban_end_day: null,
    ban_scope: null,
    min_size_cm: null,
    min_weight_kg: null,
    authority: 'MOCCAE',
    authority_type: 'federal',
    emirate: null,
    legal_ref: 'Federal Law No. 23 of 1999; Federal Law No. 24 of 1999 on Environmental Protection',
    source_url: 'https://moccae.gov.ae',
    applies_to_coast: 'Both',
    applies_to_all_species: true,
    notes: null,
  },

];

export default regulations;
