export type ConservationStatus =
  | 'Least Concern'
  | 'Near Threatened'
  | 'Vulnerable'
  | 'Endangered'
  | 'Critically Endangered'
  | 'Data Deficient'
  | 'Not Evaluated';

export type DangerLevel = 'none' | 'venomous' | 'potentially dangerous' | 'toxic' | 'dangerous';

export type Edibility = 'Excellent' | 'Good' | 'Fair' | 'Avoid' | 'Not Edible';

export type HabitatCategory = 'Reef' | 'Pelagic' | 'Demersal' | 'Coastal' | 'Open Ocean' | 'Freshwater' | 'Other';

export interface FishSpecies {
  id: string;
  slug: string;
  name: string;
  scientificName: string;
  family: string;
  habitat: string;
  habitatCategory: HabitatCategory;
  diet: string;
  maxSizeCm: number;
  maxWeightKg: number;
  conservationStatus: ConservationStatus;
  depth: string;
  regions: string[];
  description: string;
  funFacts: string[];
  edible: boolean;
  edibility: Edibility;
  dangerLevel: DangerLevel;
  colorPattern: string;
}

export function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function getHabitatCategory(habitat: string): HabitatCategory {
  const h = habitat.toLowerCase();
  if (h.includes('reef') || h.includes('coral')) return 'Reef';
  if (h.includes('open ocean') || h.includes('pelagic') || h.includes('offshore')) return 'Open Ocean';
  if (h.includes('coastal') || h.includes('estuar') || h.includes('mangrove') || h.includes('lagoon')) return 'Coastal';
  if (h.includes('sandy') || h.includes('muddy') || h.includes('sea floor') || h.includes('demersal') || h.includes('bottom')) return 'Demersal';
  if (h.includes('surface') || h.includes('tropical and subtropical ocean') || h.includes('subtropical waters')) return 'Pelagic';
  if (h.includes('river') || h.includes('freshwater') || h.includes('lake') || h.includes('stream')) return 'Freshwater';
  return 'Other';
}

function getEdibility(edible: boolean, dangerLevel: DangerLevel, name: string): Edibility {
  if (!edible) return 'Not Edible';
  if (dangerLevel === 'toxic') return 'Avoid';
  // Excellent: highly prized food fish
  const excellent = ['tuna', 'mahi', 'salmon', 'halibut', 'snapper', 'grouper', 'hammour', 'kingfish', 'cobia', 'emperor', 'bream', 'tarpon', 'wahoo'];
  const avoid = ['barracuda', 'puffer', 'moray'];
  const nameLower = name.toLowerCase();
  if (excellent.some(e => nameLower.includes(e))) return 'Excellent';
  if (avoid.some(a => nameLower.includes(a))) return 'Avoid';
  return 'Good';
}

// Raw species data inlined from fishSpecies.json
const rawSpecies = [
  {
    id: 'yellowfin-tuna',
    name: 'Yellowfin Tuna',
    scientificName: 'Thunnus albacares',
    family: 'Scombridae',
    habitat: 'Open ocean, tropical and subtropical waters',
    diet: 'Fish, squid, crustaceans',
    maxSizeCm: 239,
    maxWeightKg: 200,
    conservationStatus: 'Near Threatened' as ConservationStatus,
    depth: '0–500m',
    regions: ['Atlantic', 'Pacific', 'Indian Ocean', 'Arabian Gulf'],
    description: 'A large, fast-swimming pelagic fish prized for sport fishing and sushi. Identified by bright yellow dorsal and anal fins.',
    funFacts: ['Can swim up to 75 km/h', 'Highly migratory — crosses entire ocean basins', 'Warm-blooded, maintaining higher body temperature than surrounding water'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'metallic blue-black back, silver belly, bright yellow fins',
  },
  {
    id: 'mahi-mahi',
    name: 'Mahi Mahi',
    scientificName: 'Coryphaena hippurus',
    family: 'Coryphaenidae',
    habitat: 'Surface waters of tropical and subtropical oceans',
    diet: 'Flying fish, squid, mackerel',
    maxSizeCm: 210,
    maxWeightKg: 40,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–85m',
    regions: ['Atlantic', 'Pacific', 'Indian Ocean', 'Arabian Gulf'],
    description: 'Also called dorado, recognized by its brilliant golden-green coloring and blunt forehead. Colors fade quickly after death.',
    funFacts: ['One of the fastest-growing fish — reaches full size in 1 year', 'Can change colors rapidly when excited or dying', 'Males have a distinctive square forehead (females are rounded)'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'vivid golden-green flanks, blue-green back',
  },
  {
    id: 'red-snapper',
    name: 'Red Snapper',
    scientificName: 'Lutjanus campechanus',
    family: 'Lutjanidae',
    habitat: 'Rocky bottoms, reefs, offshore structures',
    diet: 'Fish, crustaceans, octopus',
    maxSizeCm: 100,
    maxWeightKg: 22,
    conservationStatus: 'Vulnerable' as ConservationStatus,
    depth: '10–200m',
    regions: ['Gulf of Mexico', 'Atlantic', 'Caribbean'],
    description: 'Popular sport and food fish with distinctive red coloring and large red eyes. Often found near structures and reefs.',
    funFacts: ['Can live over 50 years', 'Red eyes help them see in deep, darker water', 'Juveniles have a dark spot on their sides that fades with age'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'uniform reddish-pink body, red eyes',
  },
  {
    id: 'clownfish',
    name: 'Clownfish',
    scientificName: 'Amphiprioninae',
    family: 'Pomacentridae',
    habitat: 'Coral reefs, symbiotic with sea anemones',
    diet: 'Algae, zooplankton, small invertebrates',
    maxSizeCm: 18,
    maxWeightKg: 0.25,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '1–15m',
    regions: ['Indian Ocean', 'Pacific', 'Red Sea', 'Arabian Gulf'],
    description: 'Famous for their symbiotic relationship with sea anemones. The bright orange and white coloring warns predators.',
    funFacts: ['All clownfish are born male — dominant ones can become female', 'Immune to the stinging cells of their host anemone', "Became famous as 'Nemo' in the animated film"],
    edible: false,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'bright orange with white bands bordered by black',
  },
  {
    id: 'lionfish',
    name: 'Lionfish',
    scientificName: 'Pterois volitans',
    family: 'Scorpaenidae',
    habitat: 'Coral reefs, rocky reefs, lagoons',
    diet: 'Fish, shrimp, crabs',
    maxSizeCm: 38,
    maxWeightKg: 1.2,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '1–300m',
    regions: ['Indo-Pacific', 'Red Sea', 'Indian Ocean', 'Atlantic (invasive)'],
    description: 'Striking and venomous reef fish with elaborate fins. An invasive species in the Atlantic causing significant ecological damage.',
    funFacts: ['Venomous spines can cause extreme pain but are rarely fatal to humans', 'Invasive in the Atlantic — no natural predators outside native range', 'Can eat prey up to half their own body size'],
    edible: true,
    dangerLevel: 'venomous' as DangerLevel,
    colorPattern: 'red/white/black bands, elaborate feather-like pectoral fins',
  },
  {
    id: 'atlantic-salmon',
    name: 'Atlantic Salmon',
    scientificName: 'Salmo salar',
    family: 'Salmonidae',
    habitat: 'Cold rivers and open ocean',
    diet: 'Insects, crustaceans, small fish',
    maxSizeCm: 150,
    maxWeightKg: 46,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–600m',
    regions: ['North Atlantic', 'Arctic', 'European rivers', 'North American rivers'],
    description: 'Iconic migratory fish that travels from ocean to rivers to spawn. Silver in the ocean, develops red/brown coloring in freshwater.',
    funFacts: ['Returns to the exact river where it was born to spawn', 'Can jump up to 3.6 meters to clear waterfalls', 'Most die after spawning, but Atlantic salmon can survive and spawn multiple times'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'silver-blue in sea, pink-red spots in freshwater',
  },
  {
    id: 'blue-marlin',
    name: 'Blue Marlin',
    scientificName: 'Makaira nigricans',
    family: 'Istiophoridae',
    habitat: 'Open ocean, tropical and subtropical',
    diet: 'Mackerel, tuna, squid, dolphinfish',
    maxSizeCm: 500,
    maxWeightKg: 820,
    conservationStatus: 'Vulnerable' as ConservationStatus,
    depth: '0–500m',
    regions: ['Atlantic', 'Pacific', 'Indian Ocean', 'Arabian Gulf'],
    description: "One of the largest billfish in the world. An apex predator of the open ocean and prized sport fishing trophy.",
    funFacts: ['Uses its bill to slash through schools of fish', 'Can reach speeds of over 110 km/h', "Featured in Hemingway's 'The Old Man and the Sea'"],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'cobalt blue back, silver-white belly, pale blue vertical stripes',
  },
  {
    id: 'swordfish',
    name: 'Swordfish',
    scientificName: 'Xiphias gladius',
    family: 'Xiphiidae',
    habitat: 'Open ocean, tropical to cold temperate',
    diet: 'Fish, squid, crustaceans',
    maxSizeCm: 455,
    maxWeightKg: 650,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '200–600m',
    regions: ['Atlantic', 'Pacific', 'Indian Ocean', 'Mediterranean'],
    description: 'Solitary predator with a distinctive flat, elongated bill used for slashing prey. Highly migratory and valued for its firm flesh.',
    funFacts: ['Has a special organ that heats its brain and eyes for better vision', 'Adults have no teeth or scales', 'Can dive to 2,878 meters depth'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'dark metallic purple-blue back, lighter sides, white belly',
  },
  {
    id: 'barracuda',
    name: 'Great Barracuda',
    scientificName: 'Sphyraena barracuda',
    family: 'Sphyraenidae',
    habitat: 'Tropical and subtropical coastal waters, reefs',
    diet: 'Fish, squid',
    maxSizeCm: 200,
    maxWeightKg: 50,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–100m',
    regions: ['Atlantic', 'Pacific', 'Indian Ocean', 'Red Sea', 'Arabian Gulf'],
    description: "Fearsome predator known for its razor-sharp teeth and torpedo-shaped body. Often lurks near reefs waiting for prey.",
    funFacts: ['Attracted to shiny objects which they mistake for prey fish', 'Can accelerate to 43 km/h in short bursts', 'Large barracuda can cause ciguatera fish poisoning when eaten'],
    edible: true,
    dangerLevel: 'potentially dangerous' as DangerLevel,
    colorPattern: 'silver with dark spots, two dorsal fins set far apart',
  },
  {
    id: 'pufferfish',
    name: 'Pufferfish',
    scientificName: 'Tetraodontidae',
    family: 'Tetraodontidae',
    habitat: 'Tropical and subtropical marine waters',
    diet: 'Algae, invertebrates, mollusks',
    maxSizeCm: 90,
    maxWeightKg: 3,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '1–100m',
    regions: ['Pacific', 'Indian Ocean', 'Atlantic', 'Red Sea'],
    description: 'Famous for inflating into a spiky ball when threatened. Contains tetrodotoxin, one of the most potent natural toxins.',
    funFacts: ['Contains enough toxin to kill 30 adult humans', 'Pufferfish is a delicacy in Japan (fugu) — chefs require special licensing to prepare it', 'Inflates by swallowing water (not air)'],
    edible: false,
    dangerLevel: 'toxic' as DangerLevel,
    colorPattern: 'mottled brown/yellow with spines when inflated',
  },
  {
    id: 'hammerhead-shark',
    name: 'Hammerhead Shark',
    scientificName: 'Sphyrna mokarran',
    family: 'Sphyrnidae',
    habitat: 'Coastal and offshore tropical and warm temperate waters',
    diet: 'Fish, rays, squid, octopus',
    maxSizeCm: 610,
    maxWeightKg: 450,
    conservationStatus: 'Critically Endangered' as ConservationStatus,
    depth: '0–300m',
    regions: ['Atlantic', 'Pacific', 'Indian Ocean', 'Arabian Gulf'],
    description: 'Iconic shark recognized by its distinctive hammer-shaped head (cephalofoil) which enhances sensory perception.',
    funFacts: ['The hammer-shaped head gives 360-degree vision', "Can detect electrical signals from prey buried in sand", 'Often seen swimming with their head tilting side to side'],
    edible: false,
    dangerLevel: 'potentially dangerous' as DangerLevel,
    colorPattern: 'grey-brown back, white underside',
  },
  {
    id: 'wahoo',
    name: 'Wahoo',
    scientificName: 'Acanthocybium solandri',
    family: 'Scombridae',
    habitat: 'Tropical and subtropical open ocean',
    diet: 'Fish, squid',
    maxSizeCm: 250,
    maxWeightKg: 83,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–100m',
    regions: ['Atlantic', 'Pacific', 'Indian Ocean', 'Arabian Gulf'],
    description: 'One of the fastest fish in the ocean, highly prized for sport fishing and its delicious white flesh.',
    funFacts: ['Can reach speeds of 96 km/h', 'Known as "ono" in Hawaii meaning "delicious"', 'Has razor-sharp teeth capable of cutting fishing line'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'iridescent blue-green back, silver sides with blue vertical bars',
  },
  {
    id: 'grouper',
    name: 'Grouper (Hammour)',
    scientificName: 'Epinephelus coioides',
    family: 'Serranidae',
    habitat: 'Rocky and coral reefs',
    diet: 'Fish, crustaceans, squid',
    maxSizeCm: 120,
    maxWeightKg: 15,
    conservationStatus: 'Near Threatened' as ConservationStatus,
    depth: '1–200m',
    regions: ['Indo-Pacific', 'Red Sea', 'Arabian Gulf', 'Indian Ocean'],
    description: 'Called Hammour in the UAE, this grouper is the most prized local food fish. A solitary ambush predator found on reefs and rocky areas.',
    funFacts: ['All groupers start as females and some become male as they grow larger', 'Can change color to blend with surroundings', 'UAE national dish hammour bil tamer uses this fish'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'brownish with pale spots, can change color dramatically',
  },
  {
    id: 'flounder',
    name: 'Flounder',
    scientificName: 'Paralichthys olivaceus',
    family: 'Paralichthyidae',
    habitat: 'Sandy and muddy sea floors',
    diet: 'Fish, crustaceans, worms',
    maxSizeCm: 103,
    maxWeightKg: 9.1,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–200m',
    regions: ['Pacific', 'Indian Ocean', 'Atlantic'],
    description: 'Flat fish that lies camouflaged on the sea floor. Both eyes migrate to one side of the head as juveniles.',
    funFacts: ['Born with eyes on both sides, one eye migrates to the other side during development', 'Can change color and pattern to match surroundings in milliseconds', 'Lies flat on the seafloor with both eyes looking upward'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'mottled brown/grey top side, white underside',
  },
  {
    id: 'parrotfish',
    name: 'Parrotfish',
    scientificName: 'Scarus gibbus',
    family: 'Scaridae',
    habitat: 'Tropical coral reefs',
    diet: 'Coral, algae, invertebrates',
    maxSizeCm: 70,
    maxWeightKg: 5,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '1–30m',
    regions: ['Indo-Pacific', 'Red Sea', 'Arabian Gulf', 'Indian Ocean'],
    description: 'Colorful reef fish with beak-like teeth used to scrape algae and coral. Plays a crucial role in reef ecosystem health.',
    funFacts: ['Produces the sand on tropical beaches by excreting crushed coral', 'Can change sex and color pattern throughout their lives', 'Creates a mucus sleeping bag for protection at night'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'vivid green, blue, pink and orange patterns',
  },
  {
    id: 'blue-tang',
    name: 'Blue Tang',
    scientificName: 'Paracanthurus hepatus',
    family: 'Acanthuridae',
    habitat: 'Coral reefs',
    diet: 'Algae, plankton',
    maxSizeCm: 31,
    maxWeightKg: 0.6,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '2–40m',
    regions: ['Indo-Pacific', 'Red Sea', 'Arabian Gulf'],
    description: 'Vibrant blue reef fish made famous in animated films. Has a sharp spine near the tail for defense.',
    funFacts: ["Known as 'Dory' from the animated film Finding Nemo", 'Has a small but sharp spine near the tail that can inflict cuts', 'Plays a critical role in grazing algae off coral reefs'],
    edible: false,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'royal blue body with black markings and yellow tail',
  },
  {
    id: 'halibut',
    name: 'Pacific Halibut',
    scientificName: 'Hippoglossus stenolepis',
    family: 'Pleuronectidae',
    habitat: 'Cold coastal and offshore waters',
    diet: 'Fish, crab, squid, shrimp',
    maxSizeCm: 267,
    maxWeightKg: 333,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–1000m',
    regions: ['North Pacific', 'Bering Sea', 'Gulf of Alaska'],
    description: 'The largest of the flatfishes. A highly prized food fish with firm white flesh, found in cold northern Pacific waters.',
    funFacts: ['Can live over 55 years', 'One of the largest bony fish in the ocean', 'A single fish can produce up to 2.7 million eggs per season'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'dark brown to black on top side, white underside',
  },
  {
    id: 'cobia',
    name: 'Cobia',
    scientificName: 'Rachycentron canadum',
    family: 'Rachycentridae',
    habitat: 'Warm coastal and offshore waters',
    diet: 'Fish, crabs, squid',
    maxSizeCm: 200,
    maxWeightKg: 68,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–100m',
    regions: ['Atlantic', 'Pacific', 'Indian Ocean', 'Arabian Gulf'],
    description: 'Powerful and fast-growing sport fish known for aggressive fighting when hooked. Excellent table fare.',
    funFacts: ['Often follows sharks and rays to eat their scraps', 'Can grow up to 10 kg in a single year', 'Also called lemon fish or black kingfish'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'dark brown back, white belly, two lateral stripes',
  },
  {
    id: 'triggerfish',
    name: 'Titan Triggerfish',
    scientificName: 'Balistoides viridescens',
    family: 'Balistidae',
    habitat: 'Coral reefs and sandy areas',
    diet: 'Sea urchins, crabs, coral, mollusks',
    maxSizeCm: 75,
    maxWeightKg: 10,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '1–50m',
    regions: ['Indo-Pacific', 'Red Sea', 'Arabian Gulf', 'Indian Ocean'],
    description: 'The largest triggerfish, notoriously aggressive when guarding nests. Can inflict serious bites on divers.',
    funFacts: ['Aggressively defends a cone-shaped territory above its nest', 'Can move in any direction using its dorsal and anal fins', 'Has strong teeth capable of crushing hard corals and sea urchins'],
    edible: true,
    dangerLevel: 'potentially dangerous' as DangerLevel,
    colorPattern: 'mottled yellow-green with blue highlights on fins',
  },
  {
    id: 'giant-trevally',
    name: 'Giant Trevally',
    scientificName: 'Caranx ignobilis',
    family: 'Carangidae',
    habitat: 'Coastal coral reefs, lagoons, and open ocean',
    diet: 'Fish, cephalopods, crustaceans',
    maxSizeCm: 170,
    maxWeightKg: 80,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–188m',
    regions: ['Indo-Pacific', 'Red Sea', 'Arabian Gulf', 'Indian Ocean'],
    description: 'The largest member of the trevally family and an apex predator of reef ecosystems. Known for hunting birds by leaping from the water.',
    funFacts: ['Has been observed leaping from the water to catch low-flying seabirds', 'Juveniles mimic the color patterns of other fish for camouflage', 'Can coordinate with other species like dolphins and sharks to hunt'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'silver-grey to black, scutes along lateral line',
  },
  {
    id: 'seahorse',
    name: 'Seahorse',
    scientificName: 'Hippocampus kuda',
    family: 'Syngnathidae',
    habitat: 'Seagrass beds, coral reefs, mangroves',
    diet: 'Tiny crustaceans, plankton',
    maxSizeCm: 28,
    maxWeightKg: 0.05,
    conservationStatus: 'Vulnerable' as ConservationStatus,
    depth: '1–90m',
    regions: ['Indo-Pacific', 'Arabian Gulf', 'Red Sea'],
    description: "Unique fish that swims upright and the male carries the young. UAE waters are home to several seahorse species.",
    funFacts: ['Males become pregnant and give birth to young', 'Monogamous — mates for life in many species', 'Can change color to match surroundings for camouflage'],
    edible: false,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'yellow to brown, various patterns for camouflage',
  },
  {
    id: 'moray-eel',
    name: 'Giant Moray Eel',
    scientificName: 'Gymnothorax javanicus',
    family: 'Muraenidae',
    habitat: 'Coral reefs, rocky crevices',
    diet: 'Fish, octopus, crustaceans',
    maxSizeCm: 300,
    maxWeightKg: 30,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '1–50m',
    regions: ['Indo-Pacific', 'Red Sea', 'Arabian Gulf', 'Indian Ocean'],
    description: 'The largest moray eel species. Fearsome appearance but generally non-aggressive unless provoked.',
    funFacts: ['Has two sets of jaws — the inner jaw (pharyngeal jaw) helps pull prey into the throat', 'Poor eyesight — relies on smell to hunt', 'Cooperates with groupers to hunt fish in reef crevices'],
    edible: true,
    dangerLevel: 'potentially dangerous' as DangerLevel,
    colorPattern: 'brown/yellow with dark spots and mottled pattern',
  },
  {
    id: 'manta-ray',
    name: 'Giant Manta Ray',
    scientificName: 'Mobula birostris',
    family: 'Mobulidae',
    habitat: 'Tropical and subtropical open ocean and coastal areas',
    diet: 'Zooplankton, krill, small fish',
    maxSizeCm: 700,
    maxWeightKg: 2700,
    conservationStatus: 'Endangered' as ConservationStatus,
    depth: '0–1000m',
    regions: ['Atlantic', 'Pacific', 'Indian Ocean', 'Arabian Gulf'],
    description: 'The largest ray species with a wingspan up to 7 meters. A gentle giant that filter-feeds on plankton.',
    funFacts: ['Has the largest brain-to-body ratio of any fish', 'Can leap fully out of the water (breaching)', 'Visits cleaning stations regularly where small fish remove parasites'],
    edible: false,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'black/dark blue back, white underside with dark spots',
  },
  {
    id: 'stingray',
    name: 'Blue-Spotted Stingray',
    scientificName: 'Taeniura lymma',
    family: 'Dasyatidae',
    habitat: 'Sandy flats, coral reefs',
    diet: 'Mollusks, worms, crabs, shrimp',
    maxSizeCm: 70,
    maxWeightKg: 5,
    conservationStatus: 'Near Threatened' as ConservationStatus,
    depth: '1–30m',
    regions: ['Indo-Pacific', 'Red Sea', 'Arabian Gulf', 'Indian Ocean'],
    description: 'Strikingly beautiful ray with vivid blue spots on an olive/yellow disc. Common in UAE shallow waters.',
    funFacts: ['Has a venomous spine at the base of its tail for defense', 'Burries itself in sand to ambush prey and hide from predators', 'Often found resting in groups under coral ledges'],
    edible: false,
    dangerLevel: 'venomous' as DangerLevel,
    colorPattern: 'olive/yellow disc with vivid blue spots, blue-striped tail',
  },
  {
    id: 'napoleon-wrasse',
    name: 'Napoleon Wrasse',
    scientificName: 'Cheilinus undulatus',
    family: 'Labridae',
    habitat: 'Coral reefs, steep outer reef slopes',
    diet: 'Hard-shelled prey, mollusks, sea urchins, crabs',
    maxSizeCm: 230,
    maxWeightKg: 191,
    conservationStatus: 'Endangered' as ConservationStatus,
    depth: '1–100m',
    regions: ['Indo-Pacific', 'Red Sea', 'Arabian Gulf'],
    description: 'Also called Humphead Wrasse, this is one of the largest reef fish. Protected in UAE — critically important for reef ecosystems.',
    funFacts: ['One of few fish that can eat toxic sea stars and boxfish', 'Has a distinctive hump on its forehead that grows with age', 'Listed under CITES Appendix II — international trade regulated'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'electric blue-green with purple patterns, yellow-green juveniles',
  },
  {
    id: 'kingfish',
    name: 'Kingfish (Spanish Mackerel)',
    scientificName: 'Scomberomorus commerson',
    family: 'Scombridae',
    habitat: 'Coastal and offshore pelagic waters',
    diet: 'Fish, squid',
    maxSizeCm: 240,
    maxWeightKg: 45,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–200m',
    regions: ['Indo-Pacific', 'Red Sea', 'Arabian Gulf', 'Indian Ocean'],
    description: 'One of the most popular sport and food fish in the UAE. Fast, powerful, and highly sought after by shore anglers.',
    funFacts: ['One of the fastest fish in the sea — speeds up to 77 km/h', 'The most commercially important fish in the UAE', 'Forms large schools during feeding frenzies'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'silver sides, iridescent blue-green back, blue spots',
  },
  {
    id: 'bream',
    name: 'Sea Bream (Shaari)',
    scientificName: 'Acanthopagrus latus',
    family: 'Sparidae',
    habitat: 'Estuaries, mangroves, rocky reefs',
    diet: 'Invertebrates, mollusks, crustaceans',
    maxSizeCm: 50,
    maxWeightKg: 3,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–50m',
    regions: ['Arabian Gulf', 'Indian Ocean', 'Red Sea'],
    description: 'Called Shaari locally, this bream is extremely common in UAE waters and a popular target for shore anglers.',
    funFacts: ['Can tolerate a wide range of salinities — from freshwater to hypersaline', 'The UAE yellow-fin seabream is a distinct Arabian Gulf species', 'Often found around jetties and rocky areas'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'silver body with yellow fins, dark spot at base of pectoral fin',
  },
  {
    id: 'snook',
    name: 'Common Snook',
    scientificName: 'Centropomus undecimalis',
    family: 'Centropomidae',
    habitat: 'Coastal waters, estuaries, mangroves',
    diet: 'Fish, shrimp, crabs',
    maxSizeCm: 140,
    maxWeightKg: 24,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–20m',
    regions: ['Atlantic', 'Caribbean', 'Gulf of Mexico'],
    description: 'Highly prized sport fish known for explosive strikes and acrobatic jumps. The most sought-after inshore game fish in Florida.',
    funFacts: ['Can tolerate freshwater to full saltwater', 'Has a distinctive black lateral line running the length of the body', 'Often hunts in groups near mangrove roots'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'golden-yellow with black lateral line, yellow pectoral fins',
  },
  {
    id: 'tarpon',
    name: 'Atlantic Tarpon',
    scientificName: 'Megalops atlanticus',
    family: 'Megalopidae',
    habitat: 'Coastal waters, estuaries, rivers',
    diet: 'Fish, crabs, shrimp',
    maxSizeCm: 250,
    maxWeightKg: 161,
    conservationStatus: 'Vulnerable' as ConservationStatus,
    depth: '0–30m',
    regions: ['Atlantic', 'Caribbean', 'Gulf of Mexico', 'West Africa'],
    description: 'Prehistoric-looking fish with large silver scales. One of the most spectacular game fish — known for acrobatic leaps when hooked.',
    funFacts: ['Can breathe air directly using a modified swim bladder', 'Has scales that can be up to 7.6 cm in diameter', 'Has existed virtually unchanged for 100 million years'],
    edible: false,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'bright silver scales with a greenish-blue back',
  },
  {
    id: 'sturgeon',
    name: 'Beluga Sturgeon',
    scientificName: 'Huso huso',
    family: 'Acipenseridae',
    habitat: 'Large rivers, Caspian and Black Seas',
    diet: 'Fish, mollusks, crustaceans',
    maxSizeCm: 700,
    maxWeightKg: 1571,
    conservationStatus: 'Critically Endangered' as ConservationStatus,
    depth: '0–200m',
    regions: ['Caspian Sea', 'Black Sea', 'Azov Sea', 'European rivers'],
    description: 'The world\'s largest freshwater fish. Critically endangered due to overfishing for its prized caviar (beluga caviar).',
    funFacts: ['Can live over 100 years', 'Produces the most expensive caviar in the world', 'Has bony plates called scutes instead of scales'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'grey-brown back, pale underside, rows of bony scutes',
  },
  {
    id: 'atlantic-cod',
    name: 'Atlantic Cod',
    scientificName: 'Gadus morhua',
    family: 'Gadidae',
    habitat: 'Cold North Atlantic waters, rocky and sandy seabeds',
    diet: 'Fish, squid, crabs, worms',
    maxSizeCm: 200,
    maxWeightKg: 96,
    conservationStatus: 'Vulnerable' as ConservationStatus,
    depth: '0–600m',
    regions: ['North Atlantic', 'North Sea', 'Barents Sea', 'Labrador Sea'],
    description: 'One of the most historically important food fish in the world. Driven to near-collapse by overfishing in the 20th century.',
    funFacts: ['A single female can produce up to 9 million eggs per year', 'Once so abundant they were said to slow ships crossing the Atlantic', 'The collapse of the Grand Banks cod fishery in 1992 devastated communities across Newfoundland'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'grey-green to brown with spots, white belly, barbel under chin',
  },
  {
    id: 'emperor-fish',
    name: 'Emperor Fish (Bayadh)',
    scientificName: 'Lethrinus nebulosus',
    family: 'Lethrinidae',
    habitat: 'Coral reefs, seagrass beds, sandy areas',
    diet: 'Mollusks, crustaceans, sea urchins, small fish',
    maxSizeCm: 87,
    maxWeightKg: 8.5,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '1–75m',
    regions: ['Indo-Pacific', 'Arabian Gulf', 'Red Sea', 'Indian Ocean'],
    description: 'Called Bayadh in Arabic, this emperor fish is one of the most popular and delicious food fish in the UAE.',
    funFacts: ['Can change color rapidly — especially when stressed or excited', 'UAE restaurants consider it one of the finest local fish', 'Can produce sounds for communication by grinding their teeth'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'olive-grey to blue-green with yellow highlights, reddish fins',
  },
  {
    id: 'rainbow-trout',
    name: 'Rainbow Trout',
    scientificName: 'Oncorhynchus mykiss',
    family: 'Salmonidae',
    habitat: 'Cold, clear freshwater rivers and lakes',
    diet: 'Insects, crustaceans, small fish, worms',
    maxSizeCm: 120,
    maxWeightKg: 25,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–10m',
    regions: ['North America', 'Pacific', 'Widely introduced worldwide'],
    description: 'The most widely distributed trout species and a premier sport fish worldwide. Requires clean, cold, oxygen-rich water.',
    funFacts: ['Can have different life strategies — some migrate to sea (steelhead) while others stay in freshwater', 'The pink flesh color comes from their diet rich in crustaceans', 'Most resilient freshwater sport fish — now found on every continent except Antarctica'],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'silver-olive with a pink/red lateral stripe and black spots',
  },
  {
    id: 'pike',
    name: 'Northern Pike',
    scientificName: 'Esox lucius',
    family: 'Esocidae',
    habitat: 'Cool freshwater lakes, rivers, and streams',
    diet: 'Fish, frogs, small mammals, waterfowl',
    maxSizeCm: 150,
    maxWeightKg: 35,
    conservationStatus: 'Least Concern' as ConservationStatus,
    depth: '0–30m',
    regions: ['North America', 'Europe', 'Russia', 'Arctic'],
    description: "Apex freshwater predator known for ambush hunting in weed beds. Has rows of sharp backward-pointing teeth.",
    funFacts: ['Has been known to eat ducks and small mammals that fall into the water', 'Can remain motionless for long periods, then strike in milliseconds', "Has over 700 teeth, all pointed backward to prevent prey from escaping"],
    edible: true,
    dangerLevel: 'none' as DangerLevel,
    colorPattern: 'olive-green with cream/yellow spots and barring',
  },
];

export const fishSpecies: FishSpecies[] = rawSpecies.map((s) => ({
  ...s,
  slug: s.id,
  habitatCategory: getHabitatCategory(s.habitat),
  edibility: getEdibility(s.edible, s.dangerLevel, s.name),
}));

export function getSpeciesBySlug(slug: string): FishSpecies | undefined {
  return fishSpecies.find((s) => s.slug === slug);
}

export function getRelatedSpecies(species: FishSpecies, limit = 4): FishSpecies[] {
  return fishSpecies
    .filter((s) => s.slug !== species.slug && s.family === species.family)
    .slice(0, limit);
}

export const habitatCategories: HabitatCategory[] = ['Reef', 'Pelagic', 'Demersal', 'Coastal', 'Open Ocean', 'Freshwater'];

export const edibilityOptions: Edibility[] = ['Excellent', 'Good', 'Fair', 'Avoid', 'Not Edible'];

export const conservationStatuses: ConservationStatus[] = [
  'Least Concern',
  'Near Threatened',
  'Vulnerable',
  'Endangered',
  'Critically Endangered',
];
